export { default as About } from "./About";
export { default as Clients } from "./Clients";
export { default as Footer } from "./Footer";
export { default as KeyValueCard } from "./KeyValueCard";
export { default as KeyValues } from "./KeyValues";
export { default as Portfolio } from "./Portfolio";
export { default as PortfolioCard } from "./PortfolioCard";
export { default as SplashScreen } from "./SplashScreen";
export { default as TitlePage } from "./TitlePage";